-- MySQL Script generated by MySQL Workbench
-- Sat Aug 13 16:30:20 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema elecciones
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema elecciones
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `elecciones` ;
USE `elecciones` ;

-- -----------------------------------------------------
-- Table `elecciones`.`estates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elecciones`.`estates` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `estate` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elecciones`.`countty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elecciones`.`countty` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codeCounty` VARCHAR(6) NOT NULL,
  `county` VARCHAR(45) NOT NULL,
  `population` INT NOT NULL,
  `area` DECIMAL(11,2) NOT NULL,
  `estates_id` INT NOT NULL,
  PRIMARY KEY (`id`, `estates_id`),
  INDEX `fk_countty_estates1_idx` (`estates_id` ASC) VISIBLE,
  CONSTRAINT `fk_countty_estates1`
    FOREIGN KEY (`estates_id`)
    REFERENCES `elecciones`.`estates` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elecciones`.`election`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elecciones`.`election` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `year` VARCHAR(4) NOT NULL,
  `voteCount` INT(11) NOT NULL,
  `poloticalParty` VARCHAR(10) NOT NULL,
  `countty_id` INT NOT NULL,
  PRIMARY KEY (`id`, `countty_id`),
  INDEX `fk_election_countty_idx` (`countty_id` ASC) VISIBLE,
  CONSTRAINT `fk_election_countty`
    FOREIGN KEY (`countty_id`)
    REFERENCES `elecciones`.`countty` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elecciones`.`coordinator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elecciones`.`coordinator` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `document` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
