-- MySQL Script generated by MySQL Workbench
-- vie 12 ago 2022 11:45:07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema default_schema
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema elecciones
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `elecciones` ;

-- -----------------------------------------------------
-- Schema elecciones
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `elecciones` ;
USE `elecciones` ;

-- -----------------------------------------------------
-- Table `elecciones`.`countty`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `elecciones`.`countty` ;

CREATE TABLE IF NOT EXISTS `elecciones`.`countty` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codeCounty` VARCHAR(6) NOT NULL,
  `county` VARCHAR(45) NOT NULL,
  `population` INT NOT NULL,
  `area` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elecciones`.`poloticalParty`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `elecciones`.`poloticalParty` ;

CREATE TABLE IF NOT EXISTS `elecciones`.`poloticalParty` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Party` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elecciones`.`election`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `elecciones`.`election` ;

CREATE TABLE IF NOT EXISTS `elecciones`.`election` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `year` VARCHAR(4) NOT NULL,
  `voteCount` INT(11) NOT NULL,
  `poloticalParty_id` INT NOT NULL,
  `countty_id` INT NOT NULL,
  PRIMARY KEY (`id`, `poloticalParty_id`, `countty_id`),
  INDEX `fk_election_countty_idx` (`countty_id` ASC) VISIBLE,
  INDEX `fk_election_poloticalParty1_idx` (`poloticalParty_id` ASC) VISIBLE,
  CONSTRAINT `fk_election_countty`
    FOREIGN KEY (`countty_id`)
    REFERENCES `elecciones`.`countty` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_election_poloticalParty1`
    FOREIGN KEY (`poloticalParty_id`)
    REFERENCES `elecciones`.`poloticalParty` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elecciones`.`coordinator`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `elecciones`.`coordinator` ;

CREATE TABLE IF NOT EXISTS `elecciones`.`coordinator` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `document` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
